export const langData = {
    "en": {
        "nav-1": "home",
        "nav-2": "products",
        "nav-3": "facilities",
        "nav-4": "about",
        "nav-5": "careers",
        "nav-6": "contacts",
        "footer-bottom-1": "© 2022 - Albarella Acquacoltura",
        "footer-bottom-2": "All Rights Reserved",
        "back-to-top": "to top",
        "footer-address": "Our Location",
        "footer-socials": "Join Us",
    },
    "it": {
        "nav-1": "casa",
        "nav-2": "prodotti",
        "nav-3": "strutture",
        "nav-4": "circa",
        "nav-5": "carriere",
        "nav-6": "contatti",
        "footer-bottom-1": "© 2022 - Albarella Acquacoltura",
        "footer-bottom-2": "Tutti i diritti riservati",
        "back-to-top": "in cima alla",
        "footer-address": "La nostra Posizione",
        "footer-socials": "Unitevi",
    },
}