export const langData = {
    "en": {
        "nav-1": "home",
        "nav-2": "products",
        "nav-3": "facilities",
        "nav-4": "about",
        "nav-5": "careers",
        "nav-6": "contacts",

        "vac-title": "Available positions",
        "vac-label-1": "Aquaculture Engineer",
        "vac-label-2": "Hatchery Technician",
        "vac-label-3": "Flupsy Technician",
        "vac-det-1-pos": "Aquaculture Engineer",
        "vac-det-1-label": "position description",
        "vac-det-1-text-1": "Study, research, develop & implement ideas for hatchery production modernisation as well as workflow optimisation.",
        "vac-det-1-text-2": "Participating in optimising and increasing efficiency of other production stages involved within the shellfish lifecycle, such as pregrowing and oougrowing the shellfish to full size.",
        "vac-det-1-text-3": "Being heavily involved from the project inception and design, all the way through to startup implementation and innovation of further production facilities after the hatchery phase, such as FLUPSYs, upwelling tanks, raceway, sand lagoon based nurseries.",
        "vac-det-1-text-4": "Maintenance of various site systems like water supply / filtration systems, various electrical circuits and heating systems.",
        "vac-det-1-text-5": "Provision of Technical assistance to hatchery workers in the form of resolving equipment malfunctions.",
        "vac-det-1-text-6": "Personal innovative projects for creation of parts / systems from design phase to assembly.",
        "vac-det-1-text-7": "Observation & analysis of test results, machine error messages, and information obtained from operators in order to diagnose equipment problems.",
        "vac-det-1-text-8": "Assembly, installation and / or repair of wiring, electronic and electrical components, pipe systems and plumbing, machinery, and other aquaculture equipment.",
        "vac-det-1-btn-apply": "Apply",
        "vac-det-1-btn-close": "Close",

        "footer-address-text": "Our Location",
        "footer-address-link": "45010 Rosolina, Province of Rovigo, Italy",
        "footer-socials": "Join Us",
        "footer-contacts": "Contacts",
        "footer-bottom-text": "© 2022 - Albarella Acquacoltura",
        "footer-bottom-privacy": "All Rights Reserved",

        "btn-top": "to top",

        "form-title": "Apply for available position",
        "form-position": "Job title",
        "form-position-1": "Aquaculture Engineer/Mechanic",
        "form-position-2": "Hatchery Technician",
        "form-position-3": "Flupsy Technician",
        "form-first-name": "First name *",
        "form-last-name": "Last name *",
        "form-email": "E-mail *",
        "form-phone-number": "Phone number",
        "form-comment": "Comment",
        "form-resume-label": "Attach a resume",
        "form-resume-upload-btn": "&#10149; Choose file &lt; 5 MB, .pdf",
        "form-agreement": "I give my consent to the processing of personal data in accordance with ",
        "form-agreement-terms": "terms *",
        "form-submit": "Submit",
        "form-valid-fields-error": "Fill in the required fields",
        "form-valid-resume-ext-error": "Wrong file resolution",
        "form-valid-resume-size-error": "File size must be less than 5MB",
        "form-valid-resume-load-error": "File not loaded try again",
        "form-successfully-send": "Successfully sent",
        "form-error-send": "Failed to send form, try again",
    },
    "it": {
        "nav-1": "casa",
        "nav-2": "prodotti",
        "nav-3": "strutture",
        "nav-4": "circa",
        "nav-5": "carriere",
        "nav-6": "contatti",

        "vac-title": "Posizioni disponibili",
        "vac-label-1": "Acquacoltura Ingegnere",
        "vac-label-2": "Tecnico Di Schiuditoio",
        "vac-label-3": "Tecnico Di Flupsy",
        "vac-det-1-pos": "Acquacoltura Ingegnere",
        "vac-det-1-label": "descrizione della posizione",
        "vac-det-1-text-1": "Studiare, ricercare, sviluppare e implementare idee per la modernizzazione della produzione in schiuditoio e l'ottimizzazione del flusso di lavoro.",
        "vac-det-1-text-2": "Partecipare e aumentare l'efficienza di altre fasi di produzione coinvolte nel ciclo di vita dei molluschi, come il preingrasso e l'ingrasso a grandezza commerciale.",
        "vac-det-1-text-3": "Essere pesantemente coinvolti dall'inizio nella progettazione , fino all'avvio, ed all'implementazione e all'innovazione di ulteriori impianti di produzione dopo la fase di schiuditoio, come FLUPSY, vasche di upwelling, raceways, vivai in ambiente naturale.",
        "vac-det-1-text-4": "Manutenzione di vari sistemi del sito come approvvigionamento idrico / filtrazione impianti, circuiti elettrici vari e impianti di riscaldamento.",
        "vac-det-1-text-5": "Fornitura di assistenza tecnica agli schiuditoi sotto forma di risoluzione dei mal funzionamenti delle apparecchiature.",
        "vac-det-1-text-6": "Progetti innovativi personali per la creazione di parti/sistemi dalla fase di progettazione al montaggio.",
        "vac-det-1-text-7": "Osservazione e analisi dei risultati dei test, macchina messaggi di errore e informazioni ottenute dagli operatori per la diagnosi di eventuali problemi alle apparecchiature.",
        "vac-det-1-text-8": "Assemblaggio, installazione e / o riparazione di cablaggi, componenti elettronici ed elettrici, sistemi di tubazioni e impianti idraulici, macchinari e altre attrezzature per l'acquacoltura.",
        "vac-det-1-btn-apply": "Applicare",
        "vac-det-1-btn-close": "Vicino",


        "footer-address-text": "La nostra Posizione",
        "footer-address-link": "45010 Rosolina, Provincia di Rovigo, Italia",
        "footer-socials": "Unitevi",
        "footer-contacts": "Contatti",
        "footer-bottom-text": "© 2022 - Albarella Acquacoltura",
        "footer-bottom-privacy": "Tutti i diritti riservati",

        "btn-top": "in alto",

        "form-title": "Candidati per una posizione",
        "form-position": "Titolo di lavoro",
        "form-position-1": "Ingegnere/meccanico di acquacoltura",
        "form-position-2": "Incubatoio Tecnico",
        "form-position-3": "Flupsy Tecnico",
        "form-first-name": "Nome *",
        "form-last-name": "Cognome *",
        "form-email": "E-mail *",
        "form-phone-number": "Numero di telefono",
        "form-comment": "Commento",
        "form-resume-label": "Allegare un curriculum",
        "form-resume-upload-btn": "&#10149; Scegliere file &lt; 5 MB, .pdf",
        "form-agreement": "Do il mio consenso al trattamento dei dati personali in conformità con ",
        "form-agreement-terms": "termini *",
        "form-submit": "invia",
        "form-valid-fields-error": "Compila i campi richiesti",
        "form-valid-resume-ext-error": "Risoluzione dei file errata",
        "form-valid-resume-size-error": "La dimensione del file deve essere inferiore a 5MB",
        "form-valid-resume-load-error": "File non caricato riprova",
        "form-successfully-send": "Spedito con successo",
        "form-error-send": "Invio del modulo non riuscito, riprovare",
    },
}